### ISSUE TITLE
Publisher 'Bob Smith' is listed as ', Bob Smith' and other

### ISSUE THREAD

**Issue by blinkydoos** [eklipse2009/ZX-Pokemaster#2] opened 2017-08-21 17:39 UTC
Not sure where to report this, but the publisher Bob Smith is listed with a comma and space in front of his name -
, Bob Smith

**Comment by blinkydoos** [comment] 2017-08-21 17:52
Crystal Kingdom Dizzy 2017 gets named as -

Crystal Kingdom Dizzy 2017(2017)(-)(48K)[v1.0.4]

But it's a 128K only game. The Spectrum Computing/ZXDB site has the machine type as 'ZX-Spectrum 128 +2'.

**Comment by eklipse2009** [comment] 2017-08-21 18:36
About Smith, Bob:
This is already fixed in the upcoming version.
About Crystal Kingdom Dizzy:
This is fixable. Currently 48K is the default value for Machine Type for each file in the database. I'll change it to NULL and the game machine type will take preference when file machine type is unknown.
Thank you for your reports, they are very valuable.

**Comment by blinkydoos** [comment] 2017-08-21 19:42
So there could be a lot more with the wrong machine type ? What would happen if they were all set to NULL ?

**Comment by eklipse2009** [comment] 2017-08-21 19:43
If they are set to NULL, you will get the machine type as set in ZXDB. Please don't worry about it, just wait for the new beta version to test ;)

**Comment by blinkydoos** [comment] 2017-08-21 19:48
OK, I found a few +3 only disks anyway so I may as well report them here now (incorrectly named as 48K) -

Corruption(1988)(Rainbird)(48K)
Fish!(1989)(Rainbird)(48K)
Identify Europe(1987)(Kosmos)(48K)
Jinxter(1988)(Rainbird)(48K)

**Comment by eklipse2009** [comment] 2017-08-21 19:49
These are caused by the same bug which I've already fixed.
Thank you for reporting these.

**Comment by eklipse2009** [comment] 2017-08-21 20:47
The bug is fixed in ZX Pokemaster v1.2-beta4

**Closed by eklipse2009** 2017-08-21 20:47 UTC
